---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - heal.gxs.com
  resources:
  - reloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heal.gxs.com
  resources:
  - reloads/finalizers
  verbs:
  - update
- apiGroups:
  - heal.gxs.com
  resources:
  - reloads/status
  verbs:
  - get
  - patch
  - update
